# Generated by Django 5.0.3 on 2024-05-14 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profileImage/%Y/%m/"
                    ),
                ),
                ("book_image", models.ImageField(upload_to="bookImage/%Y/%m/")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "author_book",
                    models.CharField(
                        blank=True, default="desconhecido", max_length=100, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G", "Generico"),
                            ("F", "Ficcao"),
                            ("R", "Romance"),
                            ("T", "Terro"),
                            ("FA", "Fantasia"),
                            ("NF", "Nao ficcao"),
                            ("MHQ", "Manga e HQ"),
                        ],
                        default=("G", "Generico"),
                        max_length=50,
                        null=True,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
