# Generated by Django 5.0.4 on 2024-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookguardian", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookguardian",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Romance"),
                    ("D", "Drama"),
                    ("T", "Terro"),
                    ("A", "Aventura"),
                    ("AC", "Ação"),
                    ("S", "Suspense"),
                ],
                default="generico",
                max_length=50,
                null=True,
            ),
        ),
    ]
