# Generated by Django 5.0.4 on 2024-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookguardian", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookguardian",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Ficcao"),
                    ("R", "Romance"),
                    ("T", "Terro"),
                    ("FA", "Fantasia"),
                    ("NF", "Nao ficcao"),
                    ("MHQ", "Manga e HQ"),
                ],
                default="generico",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookguardian",
            name="author_book",
            field=models.CharField(
                blank=True, default="desconhecido", max_length=100, null=True
            ),
        ),
    ]
