# Generated by Django 5.0.3 on 2024-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookguardian", "0002_bookguardian_category_alter_bookguardian_author_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookguardian",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "Generico"),
                    ("F", "Ficcao"),
                    ("R", "Romance"),
                    ("T", "Terro"),
                    ("FA", "Fantasia"),
                    ("NF", "Nao ficcao"),
                    ("MHQ", "Manga e HQ"),
                ],
                default=("G", "Generico"),
                max_length=50,
                null=True,
            ),
        ),
    ]
